CREATE DATABASE IF NOT EXISTS db_bioskop CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE db_bioskop;
CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY,nama VARCHAR(100) NOT NULL,email VARCHAR(150) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,role ENUM('admin','user') NOT NULL DEFAULT 'user',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE film (id INT AUTO_INCREMENT PRIMARY KEY,judul VARCHAR(150) NOT NULL,genre VARCHAR(80) NOT NULL,durasi SMALLINT NOT NULL,usia TINYINT NOT NULL DEFAULT 13,sinopsis TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE jadwal (id INT AUTO_INCREMENT PRIMARY KEY,film_id INT NOT NULL,studio VARCHAR(40) NOT NULL,tanggal DATE NOT NULL,jam_mulai TIME NOT NULL,harga INT NOT NULL,kapasitas SMALLINT NOT NULL DEFAULT 80,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,CONSTRAINT jadwal_film_fk FOREIGN KEY(film_id) REFERENCES film(id));
CREATE TABLE booking (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,jadwal_id INT NOT NULL,kode_booking VARCHAR(30) NOT NULL UNIQUE,jumlah_kursi TINYINT NOT NULL,total INT NOT NULL,status ENUM('aktif','dibatalkan') NOT NULL DEFAULT 'aktif',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,CONSTRAINT booking_user_fk FOREIGN KEY(user_id) REFERENCES users(id),CONSTRAINT booking_jadwal_fk FOREIGN KEY(jadwal_id) REFERENCES jadwal(id));
INSERT INTO users(nama,email,password,role) VALUES('Administrator','admin@demo.test','$2y$10$bJGMKecAaOl2L6vqQc7InOZnIC3m45V6EnqY6touMejHCS0nH4g2e','admin'),('Budi Penonton','budi@demo.test','$2y$10$bJGMKecAaOl2L6vqQc7InOZnIC3m45V6EnqY6touMejHCS0nH4g2e','user');
INSERT INTO film(judul,genre,durasi,usia,sinopsis) VALUES('Lintasan Senja','Drama, Thriller',128,13,'Seorang fotografer menemukan potongan masa depan di setiap hasil jepretannya.'),('Orbit Terakhir','Sci-Fi',116,13,'Kru kecil berjuang membawa pulang sinyal terakhir dari orbit yang terlupakan.'),('Malam di Kota Tua','Romansa',104,13,'Dua orang asing menemukan percakapan yang mengubah malam mereka.');
INSERT INTO jadwal(film_id,studio,tanggal,jam_mulai,harga,kapasitas) VALUES(1,'Studio 1',DATE_ADD(CURDATE(),INTERVAL 1 DAY),'18:30:00',45000,80),(2,'Studio 2',DATE_ADD(CURDATE(),INTERVAL 1 DAY),'20:00:00',50000,60),(3,'Studio 1',DATE_ADD(CURDATE(),INTERVAL 2 DAY),'16:00:00',40000,80);
